### ISSUE TITLE
Grouping networks for custom-limits

### ISSUE THREAD

**Issue by Mikaela** [oragono/oragono#1421]
Currently custom-limits work by having an IP address or CIDR, but this can lead into complicated configuration in cases such as [IRCCloud.com which has 8 IPv4 addresses + 2 IPv6 ranges](https://www.irccloud.com/networks) or shell providers that connect from multiple addresses and thus require more than one `custom-limit` block.

I would like to specify IRCCloud and other services somewhere so I could add a single `custom-limit` block and adjust their limits together instead of having to manage about 14 separate blocks.

**Comment by slingamn** [comment]
One of the constraints here is backwards-compatibility for the config format. The current format is

```yaml
        custom-limits:
            "8.8.0.0/16":
                max-concurrent-connections: 128
                max-connections-per-window: 1024
```

We could change it to:

```yaml
        custom-limits:
            "google":
                nets:
                    - "8.8.0.0/16"
                    - "172.217.10.0/24"
                max-concurrent-connections: 128
                max-connections-per-window: 1024
```

and if `nets` is absent we use the dictionary key instead.
