### ISSUE TITLE
Make the opers section in the config files simpler/easier to read

### ISSUE THREAD

**Issue by DanielOaks** [oragono/oragono#1426]
Include a couple more commented-out example opers in the config file, to make it clear how real oper blocks look and how to add more, etc. Doesn't need to be anything too in-depth, just e.g.:

```yaml
opers:
    # operator named 'admin'; log in with /OPER admin [password]
    admin:
        # which capabilities this oper has access to
        class: "server-admin"

        # custom whois line
        whois-line: is a server admin

        # custom hostname
        vhost: "staff"

        # normally, operator status is visible to unprivileged users in WHO and WHOIS
        # responses. this can be disabled with 'hidden'. ('hidden' also causes the
        # 'vhost' line above to be ignored.)
        hidden: false

        # modes are modes to auto-set upon opering-up. uncomment this to automatically
        # enable snomasks ("server notification masks" that alert you to server events;
        # see `/quote help snomasks` while opered-up for more information):
        #modes: +is acjknoqtuxv

        # operators can be authenticated either by password (with the /OPER command),
        # or by certificate fingerprint, or both. if a password hash is set, then a
        # password is required to oper up (e.g., /OPER dan mypassword). to generate
        # the hash, use `oragono genpasswd`.
        password: "$2a$04$0123456789abcdef0123456789abcdef0123456789abcdef01234"

        # if a SHA-256 certificate fingerprint is configured here, then it will be
        # required to /OPER. if you comment out the password hash above, then you can
        # /OPER without a password.
        #certfp: "abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789"
        # if 'auto' is set (and no password hash is set), operator permissions will be
        # granted automatically as soon as you connect with the right fingerprint.
        #auto: true

    # oper named 'alice': /OPER alice [password]
    #alice:
    #    class: "network-oper"
    #    vhost: "staff/alice"
    #    password: "$2a$04$0123456789abcdef0123456789abcdef0123456789abcdef01234"

    # oper named 'dan': /OPER dan [password]
    #dan:
    #    class: "server-admin"
    #    vhost: "staff/dan"
    #    modes: +is acjknoqtuxv
    #    password: "$2a$04$0123456789abcdef0123456789abcdef0123456789abcdef01234"
```

**Comment by DanielOaks** [comment]
honestly we should probably just change `admin` to a real name to ensure there's no confusion about e.g. whether oper logins are shared, or that kind of thing

**Comment by DanielOaks** [comment]
in the channel, kylef mentioned that we could probably also simplify the oper-classes section too. I mostly based it on what we did in mammon's config file, but especially since we're being more than an example ircd we can make our classes better match the use cases we're seeing.

My first thoughts are that the `server-admin` class works, but I'd probably setup the `server-admin` class to be the default one, and then an example 'network-admin' class that looks exactly the same as the current `network-oper` class. Keep it to two, don't make people wonder about local-oper vs network-oper vs server-admin vs etc etc etc.

Something like this, maybe?
```yaml
# operator classes
oper-classes:
    # server admin
    "server-admin":
        # title shown in WHOIS
        title: Server Admin

        # capability names
        capabilities:
            - "accreg"
            - "chanreg"
            - "defcon"
            - "die"
            - "history"
            - "local_ban"
            - "local_kill"
            - "local_unban"
            - "nofakelag"
            - "rehash"
            - "relaymsg"
            - "roleplay"
            - "sajoin"
            - "samode"
            - "vhosts"

    # network admin
    # we don't actually have server linking, so this class isn't useful now.
    # but it's an example of extending oper classes! :)
    "network-admin":
        # title shown in WHOIS
        title: Network Admin

        # oper class this extends from
        extends: "server-admin"

        # capability names
        capabilities:
            - "remote_kill"
            - "remote_ban"
            - "remote_unban"
```

Something I really liked about the `mammon` section here is that we had some very tightly-scoped examples, like a `spam-detection-bot` that could only set specific metadata keys and that kind of thing. Once we get metadata (one day I swear), I might suggest adding something similar to our config file too ([example](https://github.com/mammon-ircd/mammon/blob/master/mammond.yml#L190)).
