### ISSUE TITLE
hopm support (connection notices)

### ISSUE THREAD

**Issue by elad661** [oragono/oragono#272]
Hi,

I've set up an Oragono server (I really appreciate how quick & easy it was, well done everyone), but I have a problem with bots connecting via TOR and other open proxy services and spamming all visible channels.

In the past when I used unrealIRCD, I installed [hopm](https://github.com/ircd-hybrid/hopm/) and that got rid of the bots. I wanted to install it on my Oragono server too, but it seems that since Oragono has no option to send connection notices to opers, there's no way hopm would work with Oragono.

It would be awesome if there was a special oper capability level that would cause connection notices to be sent to this oper, so that I could configure hopm to ban those bots.

Thanks!

**Comment by DanielOaks** [comment]
Hey @elad661!

I just threw in [this commit](https://github.com/oragono/oragono/commit/45b8d9e6fa949ce87a9987f1f9f332fbc813f57a) that makes Oragono compatible with HOPM.

With these settings and the above commit (either compiling a new copy of Oragono from scratch or waiting for the new release to drop), you should be able to have it work without any trouble:

Oragono config:
```yaml
# operator classes
oper-classes:
    # hopm
    "hopm":
        # title shown in WHOIS
        title: Proxy Monitor

        # capability names
        capabilities:
        - "oper:local_kill"
        - "oper:local_ban"
        - "oper:local_unban"
        - "nofakelag"

# ircd operators
opers:
    # operator named 'hopm'
    hopm:
        # which capabilities this oper has access to
        class: "hopm"

        # custom hostname
        vhost: "oragono.test"

        # modes are the modes to auto-set upon opering-up
        modes: +is c

        # password to login with /OPER command
        # generated using  "oragono genpasswd"
        password: JDJhJDA0JGxqbnNBN1FjSDJBR3NLMFBRTzRsRmVQODkyUXhEcnBiUFl3SVpDblVSSGJnY0dWNFM3cjZH
```

hopm config:
```c
	/* oragono */
	connregex = ".+-.+CONNECT.+-.+ Client Connected \\[([^ ]+)\\] \\[u:([^ ]+)\\] \\[h:([^ ]+)\\] \\[ip:([^ ]+)\\] .+";

	/* A DLINE example for oragono */
	kline = "DLINE ANDKILL 2h %i :Open proxy found on your host.";
```

I'll leave this issue open 'til a new release is cut and put in anyways. If you can tell me which OS you use I'll build and upload a new Oragono build you can test now if you'd like :)
