### ISSUE TITLE
/version doesn't quite work right

### ISSUE THREAD

**Issue by Nerdmaster** [oragono/oragono#296]
Asking the server its version semi-works, but results in an error:

    oragono-0.12.0-5550396 irc.<redacted>.com
    ACCCOMMANDS=CREATE,VERIFY AWAYLEN=500 CASEMAPPING=ascii CHANMODES=beI,,lk,imntEs CHANNELLEN=64 CHANTYPES=# ELIST=U EXCEPTS= INVEX= KICKLEN=1000 MAXLIST=beI:60 MAXTARGETS=4 MODES= :are supported by this server
    * :Error assembling message for sending

I think this is related to another issue we're experiencing, where half-ops register, but don't show up for clients.

**Comment by DanielOaks** [comment]
Hmm, this sounds weird. Thanks for the yell letting us know, I'll try to reproduce this on my end and see if I can see what's going on here.

**Comment by slingamn** [comment]
If you enable the "internal" logging category, the log might have more information about what's going on. Here's the logging config I'm using in production:

````yaml
logging:
    -
        method: stderr
        type: localconnect localconnect-ip quit internal rehash
        level: debug
````

See if it says anything about the half-op issue as well? (I could take a look at that independently if you have repro steps.)
