### ISSUE TITLE
Certain Unicode channel names get incorrectly rejected

### ISSUE THREAD

**Issue by remini1998** [oragono/oragono#306]
I have translated the most of text to Chinese and finally find out that it's have problem when using other language as channel name.
As a UTF-8 based irc, I think it's an important feature for all non-English users.
For now, if I join a Chinese channel by`/join #中文频道` or `/join 中文频道`, it will perform like this:
> 00:41 <myirc> Reply(403): #中文频道 No such channel

Did I do something wrong, or it's just a bug?
Perhaps it's on other considerations if it's a feature?
If it troubles the non-English users, why not make a switch in config.yaml to determine whether non-English channel could be created?

**Comment by remini1998** [comment]
I notice that the first line of the feature is:
> UTF-8 nick and channel names with rfc7613 (PRECIS)

Although I'm not familiar with the standard, but I think maybe it's a bug or caused by my config mistake. So, I decided to talk more about my tests here.
First of all, my tests tools are LimeChat (a irc client for mac) and kiwiirc (the latest code on the master). They both turned out the same result so I think the problem is not on my client.
As for the server config, all I changed manually is here:
[oragono](https://github.com/oragono/oragono/blob/master/oragono.yaml)
```
# server configuration
server:
    # server name
    name: oragono.test

    # addresses to listen on
    listen:
        - ":6667"
        - "127.0.0.1:6668"
        - "[::1]:6668"                     ←  HERE
        - ":6697" # ssl port
        # Unix domain socket for proxying:
        # - "/tmp/oragono_sock"
```
I commented the line 17 which cause docker build failed.
The other changes is make by `oragono genpasswd`.
