### ISSUE TITLE
No bouncer mode in default ircd.yaml?

### ISSUE THREAD

**Issue by poVoq** [oragono/oragono#617]
The default ircd.yaml file that gets created doesn't include the bouncer settings as explained here:
https://github.com/oragono/oragono/blob/master/docs/MANUAL.md#bouncer

**Comment by DanielOaks** [comment]
Yeah we enable the bouncer functionality, but don't automagically opt everyone in with the `allowed-by-default` flag, because reconnecting with SASL happens fairly commonly and I'm iffy on whether or not it's a good idea to expose that to users by default. I'm not totally set either way on that to be honest, but since it's new behaviour that differs from other servers (for a fairly common case) I'd like to hear more opinions before we would enable that side of it by default: https://github.com/oragono/oragono/blob/master/oragono.yaml#L328

Always appreciate feedback, will leave this issue open :)

**Comment by poVoq** [comment]
Well, it could be added to the default ircd.yaml but set to "false".
Right now it is not included at all, which makes it a bit of a guess work how to enable it.

**Comment by slingamn** [comment]
I'm confused, sorry --- does this not constitute it being included in the default ircd.yaml?

https://github.com/oragono/oragono/blob/014a5fe63c6d9ba9253318e58020274c3c6554d4/oragono.yaml#L319

**Comment by DanielOaks** [comment]
(hmm, maybe Docker hasn't been updated yet to use it or something?)

**Comment by poVoq** [comment]
Hmm, odd indeed. I am using the latest stable dockerhub release and in the file created from that it isn't there.

**Comment by slingamn** [comment]
@csmith could you take a look at this if you have time? origin/stable should be at 77372cf90f07bb54b28f72a81667c3460cd8cd4b, which should have the bouncer section in its oragono.yaml:

https://github.com/oragono/oragono/blob/77372cf90f07bb54b28f72a81667c3460cd8cd4b/oragono.yaml#L318

but apparently it's not showing up in the official docker image.

Thanks!

**Comment by DanielOaks** [comment]
Yeah our `:stable` Docker tag hasn't been getting updated, we're looking into it now. Thanks for the shout!

**Comment by DanielOaks** [comment]
@csmith the `:stable` Docker tag should be updated now, if you could give it another shot and see whether it's there now I'd appreciate it. Sorry again for the trouble, we changed some build methods between releases and forgot to update the stable files once we made the new release!

**Comment by csmith** [comment]
@DanielOaks By `:stable` do you mean `:latest`?

Both `:latest` and `:dev` docker tags have the bouncer section in though:

```yaml
    # bouncer controls whether oragono can act as a bouncer, i.e., allowing
    # multiple connections to attach to the same client/nickname identity
    bouncer:
        # when disabled, each connection must use a separate nickname (as is the
        # typical behavior of IRC servers). when enabled, a new connection that
        # has authenticated with SASL can associate itself with an existing
        # client
        enabled: true

        # clients can opt in to bouncer functionality using the cap system, or
        # via nickserv. if this is enabled, then they have to opt out instead
        allowed-by-default: false
```
