### ISSUE TITLE
more specific connection limits for networks/addresses

### ISSUE THREAD

**Issue by DanielOaks** [oragono/oragono#646]
Brought up by KoDi, the connection limit exemptions we have right now only have two settings: either an address is covered by our connection limiter or it isn't covered by it at all. However, there are cases where you may only want to boost an IP's connection limit rather than completely removing it (this is pretty common, e.g. networks allowing certain blocks like one used by IRCCloud, a public ZNC, etc to connect 350 clients but after that limit new connections will still be restricted).

Seems like a standard enough feature that'd be useful for server runners?

**Comment by slingamn** [comment]
Totally legit idea.

We should unify the limiter and the throttler, both the config and the implementation. Here's what the config might look like:

````yaml
    connection-limits:
        # whether to enforce limits on the total number of concurrent connections per IP / CIDR
        limiting: true
        # maximum concurrent connections per subnet
        max-concurrent-connections: 16

        # whether to restrict the rate of new connections per IP / CIDR
        throttling: true
        # how long to keep track of connections for
        window: 10m
        # maximum number of connections, per subnet, within the given duration
        max-connections-per-window: 32
        # how long to ban offenders for
        # after banning them, the number of connections is reset (which lets you use UNDLINE to unban people)
        throttle-ban-duration: 10m

        # how wide the cidr should be for IPv4
        cidr-len-ipv4: 32

        # how wide the cidr should be for IPv6
        cidr-len-ipv6: 64

        # IPs/networks which are exempted from connection limits
        exempted:
            - "localhost"
            # - "192.168.1.1"
            # - "2001:0db8::/32"

        # lets you set a custom limit for certain IPs/CIDRs
        special-cases:
            # - "8.8.0.0/16":
            #     max-concurrent-connections: 128
            #     max-connections-per-window: 1024
````

We may want to unify the Tor limiting code as well (but not the config, which should probably stay separate).

**Comment by DanielOaks** [comment]
Ooh, that's very interesting. I really like this idea, maybe we should workshop the name `special-cases` and how the block is structured underneath the connection name though? maybe even removing the `-` before the address name in that block (since it's more of a k:v dict rather than a list now) could make things cleaner, something along these lines?

```yaml
        # IPs/networks which are exempted from connection limits
        exempted:
            - "localhost"
            # - "192.168.1.1"
            # - "2001:0db8::/32"

        # custom connection limits for certain IPs/networks
        custom-limits:
            # "8.8.0.0/16":
            #   max-concurrent-connections: 128
            #   max-connections-per-window: 1024
```
