### ISSUE TITLE
DNSBL support

### ISSUE THREAD

**Issue by DanielOaks** [oragono/oragono#68]
Practically expected these days, makes sense to have

**Comment by DanielOaks** [comment]
I'd like to have a few different 'classes' of DNSBL matches. For instance, TOR matches should ONLY allow connections from clients that have logged in with SASL, and such. So for each DNSBL list we have hooked up:

- How it affects connections that match it (blocking entirely, requiring account, etc).
- If necessary, modifying ^ based on the 'class' that the DNSBL notes it's matched on (I think some DNSBLs report various classes based on the exact match, we should investigate that as well and see if it plays into the above).

**Comment by DanielOaks** [comment]
actions:

- **allow*: Allow the connection.
- **block**: Block the connection.
- **require-sasl**: Require the client to login via SASL before tryRegister is ended.

**Comment by moortens** [comment]
Suggestion:

* **notify**: notifies opers (perhaps a custom snomask?) that this client matches a DNSBL but no limiting action is performed

**Comment by DanielOaks** [comment]
suresure, that action sounds good to me

how's this config look?

```yaml
# dnsbls are DNS block lists. they're used to automatically deny or restrict clients who
# have been deemed bad
dnsbl:
    # whether to check DNS block lists
    enabled: false

    # channel to send rejections to if the 'notify' action is specified in any lists
    #channel: "#dnsbl"

    # the specific dnsbls to check for every client entering the network
    lists:
        -
            # host - specific hostname to use
            host: "dnsbl.dronebl.org"

            # which types of hosts to look up on this dnsbl. we support:
            # - ipv4: D.C.B.A.hostname
            # - ipv6: n.i.b.b.l.e.s.hostname (see explanation here: https://www.dan.me.uk/dnsbl )
            types:
                - ipv4
                - ipv6

            # action to take if the client matches this dnsbl:
            # - allow - let the client access the network
            # - block - block the client from accessing the network, with the given message
            # - notify - send a notification to opers in-channel (if configured) and via the 'S' snomask
            # - require-sasl - require the client to login with SASL, kill them if they don't
            action: block

            # reason that's shown if they're unable to access the network because of this rbl.
            # we support the following variables:
            # - "{ip}" - their IP address
            reason: "Your IP ({ip}) is listed in DroneBL. For assistance, see http://dronebl.org/lookup?ip={ip}"

            # specific replies to take action on. these are based on the last octet of the return IP.
            # for example, "24" or "13,54,24" would both match a result of "127.0.0.24" from the rbl.
            reply:
                # 8/9/10/11 are all proxies
                "8,9,10,11":
                    action: require-sasl
                    reason: "You need to enable SASL to access this network. For assistance, see http://dronebl.org/lookup?ip={ip}"
                # 98 is an example reply type that's not real
                98:
                    action: allow

        -
            host: "rbl.efnetrbl.org"
            types:
                - ipv4
            action: block
            reason: "Your IP ({ip}) is listed in the EFnet RBL. For assistance, see http://efnetrbl.org/?i={ip}"

        -
            host: "torexit.dan.me.uk"
            types:
                - ipv4
            action: require-sasl
            reason: "You need to enable SASL to access this network while using TOR"
```
